import type { Metadata } from 'next';
import localFont from 'next/font/local';
import Provider from './Provider';
import Header from '../components/Header';
import 'sfac-design-kit/dist/style.css';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

const pretendard = localFont({
  src: [
    {
      path: '../../public/fonts/PretendardVariable.woff2',
    },
  ],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}): JSX.Element {
  return (
    <html lang='en'>
      <body className={`relative ${pretendard.className}`}>
        <Provider>
          <Header />
          {children}
          <div id='modal'></div>
        </Provider>
      </body>
    </html>
  );
}
